# -*- coding: utf-8 -*-
"""Smiles to 2D Image.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-7ppYc9Ks9pwX2RowFxA2SUHXmkiloBI
"""

!pip install rdkit-pypi

from rdkit import Chem
from rdkit.Chem import Draw

benzene_derivatives = [
    "C1=CC=CC=C1",       # Benzene
    "CC1=CC=CC=C1",      # Toluene
    "C1=CC=C(C=C1)O",    # Phenol
    "C1=CC=C(C=C1)N",    # Aniline
    "C1=CC=C(C=C1)[N+](=O)[O-]",  # Nitrobenzene
    "C1=CC=C(C=C1)C=O",  # Benzaldehyde
    "C1=CC=C(C=C1)C(=O)O",  # Benzoic Acid
    "C1=CC=C(C=C1)Cl",   # Chlorobenzene
    "C1=CC=C(C=C1)Br",   # Bromobenzene
    "C1=CC=C(C=C1)I",    # Iodobenzene
    "CC1=CC=CC=C1",      # Ethylbenzene
    "C=CC1=CC=CC=C1",    # Styrene
    "CC(=O)C1=CC=CC=C1", # Acetophenone
    "C1=CC=C(C=C1)C#N",  # Benzonitrile
    "C1=CC(=C(C=C1)O)O"  # Catechol
]


# Loop through each SMILES and generate images
for i, smiles in enumerate(benzene_derivatives, 1):
    molecule = Chem.MolFromSmiles(smiles)
    if molecule:  # Check if the molecule is valid
        img = Draw.MolToImage(molecule)
        img.save(f"benzene_derivative_{i}.png")  # Save image
        print(f"Saved image for molecule {i}")

from google.colab import files
import os

# List the PNG files in the current directory
for filename in os.listdir():
    if filename.endswith(".png"):
        print(f"Downloading {filename}...")
        files.download(filename)